### ISSUE TITLE
eigs function error

### ISSUE THREAD

**Issue by lixiang-ucas** [Shicoder/HKS#1]
Hi,

I'm having a problem using the eigs function in OFF2HKS.m file line 50:

[evecs evals] = eigs(W, Am, nev, -1e-5);

The error that I'm getting is: 

??? Error using ==> eigs>checkInputs/LUfactorAminusSigmaB at 1136
(A-sigma*B)is singular. The shift is an eigenvalue.
Try to use some other shift please.

Error in ==> eigs>checkInputs at 899
            [L,U,pp,qq,dgAsB] = LUfactorAminusSigmaB;

Error in ==> eigs at 94
[A,Amatrix,isrealprob,issymA,n,B,classAB,k,eigs_sigma,whch, ...

**Comment by Shicoder** [comment]
Hi,
(A-sigma*B) should be an eigenvalue.According to the error messages, maybe it's just  an input error.thanks. @lixiang-ucas

**Comment by lixiang-ucas** [comment]
i'm using the SHREC14LSSTB 3D models, and your code works fine for some of the models and the others meet the above problem.  I'm wondering how to set the sigma value -1e-5 when computing eigs function. Thanks!

**Comment by Shicoder** [comment]
I never used this dataset,however,most of datasets contain incomplete 3D models.Most algorithms can not handle meshes with holes and gaps.Maybe this is the reason why you made mistakes.I suggest you fix those models first.

**Comment by lixiang-ucas** [comment]
thank your for your advice, i'll try it.
